#!/usr/bin/env python3
"""Render the committed Android-16 promotion delta from an audit snapshot."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Any


ADAPTED_RATIONALE = {
    ("build/soong", "ui/build/finder.go"):
        "Keep AOSP16 HD discovery, but gate external goldfish and exclude built-in gfxstream only for that explicit build.",
    ("device/generic/common", "treble.mk"):
        "Map removed health/keymaster/USB HIDL packages to Android-16 health, KeyMint and USB services.",
    ("device/generic/x86_64", "BoardConfig.mk"):
        "Retain the Android-16 x86_64 board, inherit common BST policy and attach only the external graphics VINTF files.",
    ("device/generic/x86_64", "android_x86_64.mk"):
        "Keep the Windows android_x86_64 identity while transferring the verified qvirt services, properties and four exclusions.",
    ("frameworks/native", "services/surfaceflinger/Scheduler/Scheduler.cpp"):
        "Implement cont.90 bst.max_fps against the Android-16 Scheduler without polling, callbacks or recursive display locking.",
    ("kernel-a16", "arch/x86/configs/bst-x86_64_defconfig"):
        "Enable the SquashFS reader required by the Windows system.sfs packaging contract.",
    ("kernel-a16", "arch/x86/kernel/setup.c"):
        "Keep the host engine instance contract tiramisu64 instead of introducing a new Baklava/qvirt identity.",
    ("system/core", "rootdir/init.rc"):
        "Place the validated AOSP16 BST services and property triggers at their Android-16 init.rc locations.",
    ("system/hwservicemanager", "Android.bp"):
        "Preserve Android-16 system_ext ownership and its /system/bin compatibility symlink instead of relocating the binary.",
}


SOURCE_MISSING_RATIONALE = {
    (".", ".gitmodules"):
        "Android-16 is a Git-submodule superproject; AOSP16 used repo metadata instead.",
    (".", "external/efibootmgr"):
        "Android-x86 target-only EFI source gitlink.",
    (".", "external/efivar"):
        "Android-x86 target-only EFI source gitlink.",
    ("device/generic/x86_64", "framework_compatibility_matrix.xml"):
        "Narrow FCM 8 bridge for the separately built legacy allocator/composer and HIDL manager.",
    ("frameworks/native", "vulkan/nulldrv/Android.bp"):
        "Remove the target null Vulkan provider while the external BST graphics provider is selected.",
    ("hardware/libhardware", "modules/gralloc/Android.bp"):
        "Remove the target default gralloc provider so exactly one BST provider owns the module name.",
    ("hardware/libhardware", "modules/hwcomposer/Android.bp"):
        "Remove the target default HWC provider so exactly one BST provider owns the module name.",
}


def esc(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def source_missing_reason(project: str, path: str) -> str:
    direct = SOURCE_MISSING_RATIONALE.get((project, path))
    if direct:
        return direct
    if project in {"external/alsa-lib", "external/alsa-utils", "external/efibootmgr", "external/efivar"}:
        return "Rename an obsolete Android.mk to .disabled because Android-16 Soong rejects this legacy Make entry point."
    return "Android-16-only structural or build-compatibility delta; see the owning project review."


def render(payload: dict[str, Any]) -> str:
    states = [state for state in payload["repositories"] if state.get("branch_delta")]
    provenance: Counter[str] = Counter()
    commit_count = file_count = additions = deletions = binary_count = 0
    for state in states:
        delta = state["branch_delta"]
        commit_count += len(delta["commits"])
        file_count += delta["changed_file_count"]
        additions += delta["added_lines"]
        deletions += delta["deleted_lines"]
        binary_count += delta["binary_file_count"]
        provenance.update(item["source_comparison"] for item in delta["changed_files"])

    summary = payload["summary"]
    lines = [
        "# Current Android-16 Promotion Delta",
        "",
        "> Generated by `scripts/generate_android16_delta_review.py` from",
        "> `promotion-audit.json`. The source reference is read-only and no AOSP16",
        "> output or binary artifact is copied into this record.",
        "",
        "## Audit Summary",
        "",
        f"- Target root: `{payload['root']}`",
        f"- Read-only source reference: `{payload.get('source_reference_root')}`",
        f"- Repositories: {summary['repositories']} total, {summary['submodules']} submodules, {summary['initialized']} initialized.",
        f"- Branches: {summary['branches'].get('aosp16-bst', 0)} `aosp16-bst`, {summary['branches'].get('aosp16-bst-merge', 0)} `aosp16-bst-merge`.",
        f"- Integrity: dirty={summary['dirty']}, detached={summary['detached']}, gitlink mismatch={summary['gitlink_mismatches']}, nonconforming commits={summary['nonconforming_commits']}.",
        f"- Promotion delta: {len(states)} repositories, {commit_count} commits, {file_count} files, +{additions}/-{deletions}, {binary_count} binary files.",
        f"- Source classification: exact={provenance['exact']}, adapted={provenance['adapted']}, source-missing={provenance['source-missing']}, target-missing={provenance['target-missing']}, type-mismatch={provenance['type-mismatch']}.",
        "",
        "`exact` means the current target file SHA-256 equals the final AOSP16 source",
        "file. `adapted` is limited to the compatibility decisions below.",
        "`source-missing` identifies Android-16 superproject structure, disabled",
        "obsolete build entries, or exactly-one-provider conflict handling.",
        "",
        "## Reviewed Non-Exact Files",
        "",
        "| Project | File | Classification | Decision |",
        "|---|---|---|---|",
    ]
    for state in states:
        project = state["path"]
        for item in state["branch_delta"]["changed_files"]:
            classification = item["source_comparison"]
            if classification == "exact":
                continue
            if classification == "adapted":
                reason = ADAPTED_RATIONALE.get(
                    (project, item["path"]), "Unclassified adaptation; publication is blocked."
                )
            elif classification == "source-missing":
                reason = source_missing_reason(project, item["path"])
            else:
                reason = "Unresolved source/target mismatch; publication is blocked."
            lines.append(
                f"| `{esc(project)}` | `{esc(item['path'])}` | `{classification}` | {esc(reason)} |"
            )

    lines.extend(["", "## Project And File Inventory", ""])
    for state in states:
        delta = state["branch_delta"]
        lines.extend(
            [
                f"### `{state['path']}`",
                "",
                f"- Head: `{state['head']}`",
                f"- Base: `{delta['base_head']}`; merge-base `{delta['merge_base']}`; ancestor={str(delta['base_is_ancestor']).lower()}.",
                f"- Delta: {len(delta['commits'])} commits, {delta['changed_file_count']} files, +{delta['added_lines']}/-{delta['deleted_lines']}, {delta['binary_file_count']} binary.",
                "",
                "Commits:",
                "",
            ]
        )
        for commit in delta["commits"]:
            lines.append(f"- `{commit['commit']}` {esc(commit['subject'])}")
        lines.extend(
            [
                "",
                "| File | + | - | Binary | Source relation |",
                "|---|---:|---:|---|---|",
            ]
        )
        for item in delta["changed_files"]:
            added = "-" if item["added"] is None else item["added"]
            deleted = "-" if item["deleted"] is None else item["deleted"]
            lines.append(
                f"| `{esc(item['path'])}` | {added} | {deleted} | "
                f"{'yes' if item['binary'] else 'no'} | `{item['source_comparison']}` |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("audit", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    payload = json.loads(args.audit.read_text(encoding="utf-8"))
    output = render(payload)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
